import random
import math

##This is the dot product in the plane.
def dot(p, q):
    return(p[0]*q[0] + p[1]*q[1])

##This tests if p1 and p2 are on the same side of
##the line generated by l1 and l2.
def isSameSide(p1, p2, l1, l2):
    t1 = [p1[0]-l1[0], p1[1]-l1[1]]
    t2 = [p2[0]-l1[0], p2[1]-l1[1]]
    n = [l1[1]-l2[1], l2[0]-l1[0]]
    return((dot(t1, n)*dot(t2,n)) > 0)

##This tests if three points that are ri along their
##sides generate a triangle that contains the center
##of the big triangle.
def containsCenter(r1, r2, r3):
    p1 = [r1, 0]
    p2 = [r2/2, r2*math.sqrt(3/4)]
    p3 = [1-r3/2, r3*math.sqrt(3/4)]
    c = [1/2, math.sqrt(1/12)]
    return (isSameSide(c, [1, 0], p1, p2) and
            isSameSide(c, [0, 0], p1, p3) and
            isSameSide(c, [0, 0], p2, p3))

##This is the main loop where I generate count random
##triangles and see if they contain the center.
count = 10000000
successes = 0

for i in range(count):
    if containsCenter(random.random(), random.random(), random.random()):
        successes += 1

print(successes/count)
print(math.log(4)/3)
